image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install -ve .
      jupyter labextension develop --overwrite .
      jlpm run build
  - command: |
      pip install -ve .
      jupyter lab --no-browser --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --NotebookApp.password=''


